import type { GridStore } from '../core/grid-store';
import type { IconRenderer } from '../icons/icon-renderer';
import type { GroupingEngine } from '../engines/grouping/grouping-engine';
export declare class GroupDropZone {
    private store;
    private groupingEngine;
    private iconRenderer;
    private el;
    private chipsEl;
    private dockPos;
    private outerRowEl;
    private mainColEl;
    private isDockDragging;
    private dockIndicatorEl;
    private _onDockMove;
    private _onDockUp;
    private draggingChipId;
    private chipGhostEl;
    private chipDropIndex;
    private _onChipMove;
    private _onChipUp;
    private isResizing;
    private resizeStartSize;
    private resizeStartPos;
    private _onResizeMove;
    private _onResizeUp;
    private searchCallback;
    private searchInputEl;
    private searchClearEl;
    private searchDebounceTimer;
    constructor(store: GridStore, groupingEngine: GroupingEngine, iconRenderer: IconRenderer);
    mount(outerRowEl: HTMLElement, mainColEl: HTMLElement): void;
    update(): void;
    highlight(on: boolean): void;
    isOver(x: number, y: number): boolean;
    isGrouped(colId: string): boolean;
    dropColumn(colId: string): void;
    removeColumn(colId: string): void;
    setSearchCallback(fn: (term: string) => void): void;
    destroy(): void;
    private buildStructure;
    private render;
    private startDockDrag;
    private onDockMove;
    private onDockUp;
    private setDock;
    private cleanupDockDrag;
    private startChipDrag;
    private onChipMove;
    private onChipUp;
    private cleanupChipDrag;
    private startResize;
    private onResizeMove;
    private cleanupResize;
}
//# sourceMappingURL=group-drop-zone.d.ts.map