import { GridCore } from '../src/index';
import type { ColumnDef } from '../src/types/column.types';
import type { GridOptions } from '../src/types/grid.types';

/**
 * Standalone Master/Detail demo — a record-label inventory grid.
 * Expanding a release shows its physical variants (LP/CD/Cassette pressings)
 * in a fully independent nested Photon Grid, driven by `masterDetail`.
 */

// ─── Data model ────────────────────────────────────────────────────────────

interface ReleaseVariant {
  title: string;
  available: number;
  format: string;
  label: string;
  country: string;
  catNo: string;
  year: number;
}

/** Third nesting level: where a variant's available stock physically sits. Demonstrates that `masterDetail.detailGrid` is itself a full `GridOptions`, so it can declare its own `masterDetail` for unlimited depth. */
interface VariantStockLocation {
  warehouse: string;
  city: string;
  qty: number;
  restockDate: string;
}

type ReleaseStatus = 'Active' | 'Out of Stock' | 'On Hold';

interface Release {
  id: number;
  albumName: string;
  genre: string;
  coverGradient: string;
  coverLabel: string;
  artist: string;
  year: number;
  status: ReleaseStatus;
  stock: number;
  incoming: number;
  price: number;
  priceChangePct: number;
  sold: number;
  estProfit: number;
  variants: ReleaseVariant[];
}

function asRelease(row: Record<string, unknown>): Release {
  return row as unknown as Release;
}

function asVariant(row: Record<string, unknown>): ReleaseVariant {
  return row as unknown as ReleaseVariant;
}

/** Warehouses a variant's stock can be split across — deterministic, not stored per-variant, purely to demonstrate a third `masterDetail` level with derived (not static) detail data. */
const STOCK_WAREHOUSES: ReadonlyArray<{ warehouse: string; city: string }> = [
  { warehouse: 'Central DC', city: 'London' },
  { warehouse: 'North Hub', city: 'Manchester' },
  { warehouse: 'Overseas DC', city: 'Rotterdam' },
];

function buildStockLocations(variant: ReleaseVariant): VariantStockLocation[] {
  if (variant.available <= 0) return [];
  const count = Math.min(STOCK_WAREHOUSES.length, Math.max(1, Math.ceil(variant.available / 4)));
  const locations = STOCK_WAREHOUSES.slice(0, count);
  const perLocation = Math.floor(variant.available / locations.length);
  const remainder = variant.available - perLocation * locations.length;
  return locations.map((loc, i) => ({
    warehouse: loc.warehouse,
    city: loc.city,
    qty: perLocation + (i === 0 ? remainder : 0),
    restockDate: `2026-08-0${i + 1}`,
  }));
}

// ─── Static demo data ──────────────────────────────────────────────────────

export const releases: Release[] = [
  {
    id: 1,
    albumName: 'Dreams of You',
    genre: 'Soft Rock',
    coverGradient: 'linear-gradient(135deg, #fb923c, #ec4899)',
    coverLabel: 'DY',
    artist: 'David Nearing',
    year: 1978,
    status: 'Active',
    stock: 8,
    incoming: 20,
    price: 32,
    priceChangePct: 5,
    sold: 18,
    estProfit: 57.6,
    variants: [
      { title: 'Dreams of You', available: 5, format: 'LP, Album, Reissue', label: 'Amberline Records', country: 'Worldwide', catNo: 'ARL1978-01', year: 2024 },
      { title: 'Dreams of You', available: 3, format: 'CD, Album, Remastered', label: 'Amberline Records', country: 'Europe', catNo: 'ARCD-78X', year: 2024 },
      { title: 'Dreams of You', available: 3, format: 'CD, Album, Remastered', label: 'Amberline Records', country: 'Europe', catNo: 'ARCD-78X', year: 2024 },
      { title: 'Dreams of You', available: 3, format: 'CD, Album, Remastered', label: 'Amberline Records', country: 'Europe', catNo: 'ARCD-78X', year: 2024 },
      { title: 'Dreams of You', available: 3, format: 'CD, Album, Remastered', label: 'Amberline Records', country: 'Europe', catNo: 'ARCD-78X', year: 2024 },
      { title: 'Dreams of You', available: 3, format: 'CD, Album, Remastered', label: 'Amberline Records', country: 'Europe', catNo: 'ARCD-78X', year: 2024 },
      { title: 'Dreams of You', available: 3, format: 'CD, Album, Remastered', label: 'Amberline Records', country: 'Europe', catNo: 'ARCD-78X', year: 2024 },
      { title: 'Dreams of You', available: 3, format: 'CD, Album, Remastered', label: 'Amberline Records', country: 'Europe', catNo: 'ARCD-78X', year: 2024 },
      { title: 'Dreams of You', available: 3, format: 'CD, Album, Remastered', label: 'Amberline Records', country: 'Europe', catNo: 'ARCD-78X', year: 2024 },
      { title: 'Dreams of You', available: 3, format: 'CD, Album, Remastered', label: 'Amberline Records', country: 'Europe', catNo: 'ARCD-78X', year: 2024 },
      { title: 'Dreams of You', available: 3, format: 'CD, Album, Remastered', label: 'Amberline Records', country: 'Europe', catNo: 'ARCD-78X', year: 2024 },
      { title: 'Dreams of You', available: 3, format: 'CD, Album, Remastered', label: 'Amberline Records', country: 'Europe', catNo: 'ARCD-78X', year: 2024 },
      { title: 'Dreams of You', available: 3, format: 'CD, Album, Remastered', label: 'Amberline Records', country: 'Europe', catNo: 'ARCD-78X', year: 2024 },
      { title: 'Dreams of You', available: 3, format: 'CD, Album, Remastered', label: 'Amberline Records', country: 'Europe', catNo: 'ARCD-78X', year: 2024 },
      { title: 'Dreams of You', available: 3, format: 'CD, Album, Remastered', label: 'Amberline Records', country: 'Europe', catNo: 'ARCD-78X', year: 2024 },
      { title: 'Dreams of You', available: 3, format: 'CD, Album, Remastered', label: 'Amberline Records', country: 'Europe', catNo: 'ARCD-78X', year: 2024 },
      { title: 'Dreams of You', available: 3, format: 'CD, Album, Remastered', label: 'Amberline Records', country: 'Europe', catNo: 'ARCD-78X', year: 2024 },
      { title: 'Dreams of You', available: 3, format: 'CD, Album, Remastered', label: 'Amberline Records', country: 'Europe', catNo: 'ARCD-78X', year: 2024 },
      { title: 'Dreams of You', available: 3, format: 'CD, Album, Remastered', label: 'Amberline Records', country: 'Europe', catNo: 'ARCD-78X', year: 2024 },
      { title: 'Dreams of You', available: 3, format: 'CD, Album, Remastered', label: 'Amberline Records', country: 'Europe', catNo: 'ARCD-78X', year: 2024 },
      { title: 'Dreams of You', available: 3, format: 'CD, Album, Remastered', label: 'Amberline Records', country: 'Europe', catNo: 'ARCD-78X', year: 2024 },
      { title: 'Dreams of You', available: 3, format: 'CD, Album, Remastered', label: 'Amberline Records', country: 'Europe', catNo: 'ARCD-78X', year: 2024 },
      { title: 'Dreams of You', available: 3, format: 'CD, Album, Remastered', label: 'Amberline Records', country: 'Europe', catNo: 'ARCD-78X', year: 2024 },
      { title: 'Dreams of You', available: 3, format: 'CD, Album, Remastered', label: 'Amberline Records', country: 'Europe', catNo: 'ARCD-78X', year: 2024 },
      { title: 'Dreams of You', available: 3, format: 'CD, Album, Remastered', label: 'Amberline Records', country: 'Europe', catNo: 'ARCD-78X', year: 2024 },
      { title: 'Dreams of You', available: 3, format: 'CD, Album, Remastered', label: 'Amberline Records', country: 'Europe', catNo: 'ARCD-78X', year: 2024 },
      { title: 'Dreams of You', available: 3, format: 'CD, Album, Remastered', label: 'Amberline Records', country: 'Europe', catNo: 'ARCD-78X', year: 2024 },
    ],
  },
  {
    id: 2,
    albumName: 'Blue Skies',
    genre: 'Pop',
    coverGradient: 'linear-gradient(135deg, #38bdf8, #6366f1)',
    coverLabel: 'BS',
    artist: 'Maya Allen',
    year: 2022,
    status: 'Out of Stock',
    stock: 0,
    incoming: 0,
    price: 25,
    priceChangePct: 10,
    sold: 12,
    estProfit: 30,
    variants: [
      { title: 'Blue Skies', available: 0, format: 'LP, Album', label: 'Skyline Records', country: 'Worldwide', catNo: 'SKY2022-01', year: 2022 },
    ],
  },
  {
    id: 3,
    albumName: 'Heaven',
    genre: 'Synth-pop',
    coverGradient: 'linear-gradient(135deg, #a855f7, #6366f1)',
    coverLabel: 'HV',
    artist: 'Velvet Wave',
    year: 1989,
    status: 'Active',
    stock: 10,
    incoming: 5,
    price: 20,
    priceChangePct: 10,
    sold: 5,
    estProfit: 10,
    variants: [
      { title: 'Heaven', available: 6, format: 'LP, Album, Reissue', label: 'Nightfall Records', country: 'Worldwide', catNo: 'NFR1989-01', year: 2023 },
      { title: 'Heaven', available: 4, format: 'Cassette, Album', label: 'Nightfall Records', country: 'Europe', catNo: 'NFR1989-CS', year: 1989 },
    ],
  },
  {
    id: 4,
    albumName: 'Life Matters',
    genre: 'Rhythm & Blues',
    coverGradient: 'linear-gradient(135deg, #f59e0b, #d97706)',
    coverLabel: 'LM',
    artist: 'Danielle James',
    year: 2007,
    status: 'On Hold',
    stock: 4,
    incoming: 15,
    price: 28,
    priceChangePct: 5,
    sold: 9,
    estProfit: 25.2,
    variants: [
      { title: 'Life Matters', available: 2, format: 'CD, Album', label: 'Soulwave Records', country: 'United States', catNo: 'SWR2007-CD', year: 2007 },
      { title: 'Life Matters', available: 2, format: 'LP, Album', label: 'Soulwave Records', country: 'Worldwide', catNo: 'SWR2007-LP', year: 2007 },
    ],
  },
  {
    id: 5,
    albumName: 'Lonely Hearts',
    genre: 'Alt-pop',
    coverGradient: 'linear-gradient(135deg, #f472b6, #f43f5e)',
    coverLabel: 'LH',
    artist: 'Emma Stone',
    year: 2023,
    status: 'Active',
    stock: 14,
    incoming: 24,
    price: 34,
    priceChangePct: 12,
    sold: 17,
    estProfit: 57.8,
    variants: [
      { title: 'Lonely Hearts', available: 14, format: 'LP, Album, Colored Vinyl', label: 'Aurora Records', country: 'Worldwide', catNo: 'AUR2023-01', year: 2023 },
    ],
  },
  {
    id: 6,
    albumName: 'Imaginary Groove',
    genre: 'Jazz',
    coverGradient: 'linear-gradient(135deg, #34d399, #0ea5e9)',
    coverLabel: 'IG',
    artist: 'Leo Collins',
    year: 1972,
    status: 'Active',
    stock: 6,
    incoming: 10,
    price: 30,
    priceChangePct: 8,
    sold: 8,
    estProfit: 24,
    variants: [
      { title: 'Imaginary Groove', available: 3, format: 'LP, Album, Reissue', label: 'Bluebeat Records', country: 'Worldwide', catNo: 'BBR1972-01', year: 2021 },
      { title: 'Imaginary Groove', available: 3, format: 'CD, Compilation', label: 'Bluebeat Records', country: 'Europe', catNo: 'BBR1972-CD', year: 2015 },
    ],
  },
  {
    id: 7,
    albumName: 'Neon Wilderness',
    genre: 'Electronic',
    coverGradient: 'linear-gradient(135deg, #22d3ee, #3b82f6)',
    coverLabel: 'NW',
    artist: 'Rico Vane',
    year: 2019,
    status: 'Active',
    stock: 22,
    incoming: 30,
    price: 27,
    priceChangePct: 6,
    sold: 41,
    estProfit: 110.7,
    variants: [
      { title: 'Neon Wilderness', available: 12, format: 'LP, Album, Splatter Vinyl', label: 'Circuit Records', country: 'Worldwide', catNo: 'CIR2019-01', year: 2019 },
      { title: 'Neon Wilderness', available: 10, format: 'Digital, Album', label: 'Circuit Records', country: 'Worldwide', catNo: 'CIR2019-DL', year: 2019 },
    ],
  },
  {
    id: 8,
    albumName: 'Paper Moons',
    genre: 'Indie Folk',
    coverGradient: 'linear-gradient(135deg, #fbbf24, #f97316)',
    coverLabel: 'PM',
    artist: 'Willow Hart',
    year: 2015,
    status: 'On Hold',
    stock: 3,
    incoming: 0,
    price: 22,
    priceChangePct: 2,
    sold: 6,
    estProfit: 13.2,
    variants: [
      { title: 'Paper Moons', available: 3, format: 'LP, Album', label: 'Hollow Tree Records', country: 'United States', catNo: 'HTR2015-01', year: 2015 },
    ],
  },
  {
    id: 9,
    albumName: 'Static Bloom',
    genre: 'Shoegaze',
    coverGradient: 'linear-gradient(135deg, #818cf8, #c084fc)',
    coverLabel: 'SB',
    artist: 'Ferric Skye',
    year: 2021,
    status: 'Active',
    stock: 17,
    incoming: 12,
    price: 26,
    priceChangePct: 4,
    sold: 22,
    estProfit: 57.2,
    variants: [
      { title: 'Static Bloom', available: 9, format: 'LP, Album', label: 'Wavelength Records', country: 'Worldwide', catNo: 'WLR2021-01', year: 2021 },
      { title: 'Static Bloom', available: 5, format: 'CD, Album', label: 'Wavelength Records', country: 'Europe', catNo: 'WLR2021-CD', year: 2021 },
      { title: 'Static Bloom', available: 3, format: 'Cassette, Album, Ltd. Edition', label: 'Wavelength Records', country: 'Worldwide', catNo: 'WLR2021-CS', year: 2021 },
    ],
  },
  {
    id: 10,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 11,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 12,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 13,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 14,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 15,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 16,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 17,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 18,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 19,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 20,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 20,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 21,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 22,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 10,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 10,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 10,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 10,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 10,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 10,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 10,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 10,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 10,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 10,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 10,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 10,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 10,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 10,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 10,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 10,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 10,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 10,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 10,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 10,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 10,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 10,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 10,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 10,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 10,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 10,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 10,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 10,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 10,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 10,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 10,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 10,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 10,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 10,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 10,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 10,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 10,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 10,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 10,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 10,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 10,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 10,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 10,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 10,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 10,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 10,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 10,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 10,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 10,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 10,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 10,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 10,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 10,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 10,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 10,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 10,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 10,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 10,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 10,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 10,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 10,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 10,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 10,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 10,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 10,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 10,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 10,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 10,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 10,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 10,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 10,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 10,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 10,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 10,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 10,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 10,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 10,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 10,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 10,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 10,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 10,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 10,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 10,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 10,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 10,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 10,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 10,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 10,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 10,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 10,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 10,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 10,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 10,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 10,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 10,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 10,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 10,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 10,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 10,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 10,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 10,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 10,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 10,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
  {
    id: 10,
    albumName: 'Concrete Garden',
    genre: 'Hip-Hop',
    coverGradient: 'linear-gradient(135deg, #4ade80, #16a34a)',
    coverLabel: 'CG',
    artist: 'Nova Reign',
    year: 2020,
    status: 'Out of Stock',
    stock: 0,
    incoming: 8,
    price: 24,
    priceChangePct: 15,
    sold: 33,
    estProfit: 79.2,
    variants: [
      { title: 'Concrete Garden', available: 0, format: 'LP, Album', label: 'Uptown Records', country: 'United States', catNo: 'UPR2020-01', year: 2020 },
    ],
  },
];

// ─── Column definitions ─────────────────────────────────────────────────────

export const inventoryColumns: ColumnDef[] = [
  {
    colId: 'albumName',
    field: 'albumName',
    header: 'Album Name',
    type: 'string',
    pinned: null,
    minWidth: 220,
    width: 220,
    sortable: true,
    filterable: true,
    groupable: true,
    renderer: {
      display: ({ row }) => {
        const r = asRelease(row);
        const wrap = document.createElement('div');
        wrap.className = 'inv-album-cell';

        const cover = document.createElement('div');
        cover.className = 'inv-cover';
        cover.style.background = r.coverGradient;
        cover.textContent = r.coverLabel;

        const textCol = document.createElement('div');
        textCol.className = 'inv-album-text';

        const title = document.createElement('div');
        title.className = 'inv-album-title';
        title.textContent = r.albumName;

        const badge = document.createElement('div');
        badge.className = 'inv-genre-badge';
        badge.textContent = r.genre;

        textCol.appendChild(title);
        textCol.appendChild(badge);
        wrap.appendChild(cover);
        wrap.appendChild(textCol);
        return r.genre && r.albumName ? wrap: '';
      },
    },
  },
  { colId: 'artist', field: 'artist', header: 'Artist', type: 'string', rowDrag: true, minWidth: 140, sortable: true, filterable: true, groupable: true },
  { colId: 'year', field: 'year', header: 'Year', type: 'number', width: 90, sortable: true },
  {
    colId: 'status',
    field: 'status',
    header: 'Status',
    type: 'dropdown',
    width: 140,
    sortable: true,
    filterable: true,
    groupable: true,
    dropdownOptions: [
      { value: 'Active', label: 'Active', color: '#16a34a' },
      { value: 'Out of Stock', label: 'Out of Stock', color: '#dc2626' },
      { value: 'On Hold', label: 'On Hold', color: '#d97706' },
    ],
  },
  {
    colId: 'inventory',
    field: 'stock',
    header: 'Inventory',
    type: 'string',
    width: 170,
    renderer: {
      display: ({ row }) => {
        const r = asRelease(row);
        return r.stock != null ?   `${r.stock} Stock / ${r.variants.length} Variant${r.variants.length === 1 ? '' : 's'}`: '';
      },
    },
  },
  { colId: 'incoming', field: 'incoming', header: 'Incoming', type: 'number', width: 100, sortable: true },
  {
    colId: 'price',
    field: 'price',
    header: 'Price',
    type: 'currency',
    width: 130,
    sortable: true,
    renderer: {
      display: ({ row }) => {
        const r = asRelease(row);
        const wrap = document.createElement('div');
        wrap.className = 'inv-price-cell';
        const amount = document.createElement('div');
        amount.className = 'inv-price-amount';
        amount.textContent = `£${r.price}`;
        const sub = document.createElement('div');
        sub.className = 'inv-price-sub';
        sub.textContent = `${r.priceChangePct}% increase`;
        wrap.appendChild(amount);
        wrap.appendChild(sub);
        return r.price ? wrap: '';
      },
    },
  },
  { colId: 'sold', field: 'sold', header: 'Sold', type: 'number', width: 90, sortable: true },
  {
    colId: 'estProfit',
    field: 'estProfit',
    header: 'Est. Profit',
    type: 'currency',
    width: 120,
    sortable: true,
    renderer: {
      display: ({ row }) => `£${asRelease(row).estProfit.toFixed(1)}`,
    },
  },
  {
    colId: 'actions',
    field: 'id',
    header: 'Actions',
    type: 'custom',
    pinned: null,
    width: 190,
    resizable: false,
    renderer: {
      display: ({ row, rowIndex }) => {
        const r = asRelease(row);
        const wrap = document.createElement('div');
        wrap.className = 'inv-actions-cell';

        const holdBtn = document.createElement('button');
        holdBtn.type = 'button';
        holdBtn.className = 'inv-btn inv-btn--hold';
        holdBtn.textContent = 'Hold Selling';
        holdBtn.addEventListener('click', (e) => {
          e.stopPropagation();
          const held = holdBtn.classList.toggle('inv-btn--held');
          holdBtn.textContent = held ? 'Resume Selling' : 'Hold Selling';
        });

        const delBtn = document.createElement('button');
        delBtn.type = 'button';
        delBtn.className = 'inv-btn inv-btn--icon';
        delBtn.setAttribute('aria-label', `Remove ${r.albumName}`);
        delBtn.title = `Remove ${r.albumName}`;
        delBtn.innerHTML = '<svg viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" width="14" height="14"><path d="M2 4H14M5 4V2H11V4M6 7V12M10 7V12M3 4L4 14H12L13 4" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/></svg>';
        delBtn.addEventListener('click', (e) => {
          e.stopPropagation();
          if (!confirm(`Remove "${r.albumName}" from inventory?`)) return;
          const node = grid.api.getRowByIndex(rowIndex);
          if (node) grid.api.removeRows([node.nodeId]);
        });

        wrap.appendChild(holdBtn);
        wrap.appendChild(delBtn);
        return wrap;
      },
    },
  },
];

// ─── Master/Detail: nested "release variants" grid ─────────────────────────

const variantColumns: ColumnDef[] = [
  { colId: 'title', field: 'title', header: 'Title', type: 'string', minWidth: 120, sortable: true },
  { colId: 'available', field: 'available', header: 'Available', type: 'number', width: 90, sortable: true },
  { colId: 'format', field: 'format', header: 'Format', type: 'string',  minWidth: 160, sortable: true },
  { colId: 'label', field: 'label', header: 'Label', type: 'string', minWidth: 120, sortable: true },
  { colId: 'country', field: 'country', header: 'Country', type: 'string', minWidth: 100, sortable: true },
  { colId: 'catNo', field: 'catNo', header: 'Cat#', type: 'string', width: 110, sortable: true },
  { colId: 'year', field: 'year', header: 'Year', type: 'number', width: 100, sortable: true },
];

// ─── Master/Detail: third level — "stock locations" per variant ───────────
// `masterDetail.detailGrid` is itself a full `GridOptions`, so it can declare
// its own `masterDetail` — nesting is not hardcoded to two levels anywhere in
// the engine, it is just recursion through the same config shape.

const stockLocationColumns: ColumnDef[] = [
  { colId: 'warehouse', field: 'warehouse', header: 'Warehouse', type: 'string', minWidth: 130, sortable: true },
  { colId: 'city', field: 'city', header: 'City', type: 'string', minWidth: 120, sortable: true },
  { colId: 'qty', field: 'qty', header: 'Qty', type: 'number', width: 80, sortable: true },
  { colId: 'restockDate', field: 'restockDate', header: 'Restock Date', type: 'string', width: 130, sortable: true },
];


// Look to the GridOptions how it support multiple and nested master/detail grids. The `masterDetail` property is defined in the `GridOptions` interface, and it allows you to specify whether a grid has a master/detail relationship, how to toggle the detail view, and how to retrieve the detail data for each row. 
const options: GridOptions = {
  columns: inventoryColumns,
  data: releases as unknown as Record<string, unknown>[],
  theme: 'light',
  rowHeight: 78,
  headerRowHeight: 40,
  showCheckboxes: false,
  showSerialNumber: false,
  showVerticalBorders: false,
  showFooter: false,
  enableCellSelection: true,

  masterDetail: {
    enabled: true,
    toggleColumnId: 'albumName',
    getDetailData: (row) => asRelease(row).variants as unknown as Record<string, unknown>[],
    detailGrid: {
      columns: variantColumns,
      rowHeight: 34,
      headerRowHeight: 36,
      showFooter: false,
      showVerticalBorders: true,
      showGroupingBar: false,

      // Third level: expanding a variant row shows where its stock physically
      // sits. Configuring further nesting is just adding another
      // `masterDetail` block to this level's own `detailGrid` — the same
      // shape as the level above, to any depth.
      masterDetail: {
        enabled: true,
        toggleColumnId: 'title',
        hasDetail: (row) => asVariant(row).available > 0,
        getDetailData: (row) => buildStockLocations(asVariant(row)) as unknown as Record<string, unknown>[],
        detailGrid: {
          columns: stockLocationColumns,
          rowHeight: 30,
          headerRowHeight: 32,
          showFooter: false,
          showVerticalBorders: true,
          showGroupingBar: false,
        },
        detailAutoHeight: true,
        detailMinHeight: 60,
        detailMaxHeight: 200,
      },
    },
    detailAutoHeight: true,
    detailMinHeight: 90,
    detailMaxHeight: 380,
  },
  photonAI: {
    enabled: true,
  },
};

// ─── Bootstrap ───────────────────────────────────────────────────────────────

let grid: GridCore;

document.addEventListener('DOMContentLoaded', () => {
  const container = document.getElementById('grid-container')!;
  grid = new GridCore(container, options);
});
